import "./globals.css";
import { Hanken_Grotesk } from "next/font/google";
import { StoreProvider } from "@/redux/store/StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const hanken = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Tripiphy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hanken.className}>
        <>
          <StoreProvider>{children}</StoreProvider>
          <ToastContainer />
        </>
      </body>
    </html>
  );
}
